name: Release Docker Image

on:
  workflow_dispatch:

jobs:
  release_image:
    uses: pagopa/dx/.github/workflows/docker_image_build.yaml@DEVEX-38-produrre-una-pipeline-per-la-pubblicazione-di-unimmagine-container-sul-registry
    name: Docker Image
    secrets: inherit
    with:
      dockerfile_path: './apps/Dockerfile'
      image_description: 'Empty image used for tests'
      build_args: |
        ENV_KEY=override_arg_value
        ENV_KEY2=override_arg_value2
