name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Trigger the workflow when resources are modified
      - "infra/resources"

jobs:
  release_prod:
    uses: ./.github/workflows/infra_apply.yaml
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      region: westeurope
      base_path: infra/resources
