name: GitHub Repo Builder

on:
  workflow_dispatch:
    inputs:
      technology:
        type: choice
        default: 'typescript'
        required: true
        description: 'Choose your technology stack'
        options:
          - typescript
      name:
        type: string
        required: true
        description: 'New repository name'

jobs:

  builder:
    name: 'Builder'
    runs-on: ubuntu-20.04

    steps:

      - name: 'Create repo from template'
        run: |
          gh repo create pagopa/${{ inputs.name }} \
            --private \
            --disable-wiki \
            --template pagopa/${{ inputs.technology }}-template

  repo_setup:
    name: 'Repository setup'
    runs-on: ubuntu-20.04
    needs: [builder]
    environment: prod-cd
    env:
      ARM_USE_OIDC: true
      ARM_USE_AZUREAD: true
      ARM_STORAGE_USE_AZUREAD: true
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v4
        name: Checkout new repo
        with:
          repository: pagopa/${{ inputs.name }}
          path: repo
          token: ${{ secrets.GH_PAT }}

      - name: Replace placeholders
        working-directory: repo
        run: |
          find . -type f -exec sed -i 's/terraform-state-rg/dev-anderag/g; s/<your-environment>/prod/g; s/<your-project>/dotnet/g; s/<your-repo-name>/dotnet-app2/g' {} +

      - name: Push changes
        working-directory: repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "setup repo settings"
          git push origin main

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform

      - name: Terraform Init
        working-directory: repo/infra/repository
        run: |
          terraform init -backend-config="backend.tfvars"

      - name: Terraform Plan
        working-directory: repo/infra/repository
        run: |
          terraform plan
        
      - name: Terraform Apply
        working-directory: repo/infra/repository
        run: |
          terraform apply --auto-approve